name: GitHub Actions Workflows

on:
  push:
    branches:
      - '*'  # Trigger on any branch push
  pull_request:
    branches:
      - '*'  # Trigger on any branch pull request

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger webhook
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"event": "action"}' http://127.0.0.1:5000/webhook

