name: GitHub Actions Workflows

on:
  push:
    branches:
      - '*'  # Trigger on any branch push
  pull_request:
    branches:
      - '*'  # Trigger on any branch pull request

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger webhook
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"event": "action"}' https://b6e5-2409-408c-be90-3ec1-f855-a7a0-5aed-8337.ngrok-free.app/webhook

